### ISSUE TITLE
CajeroView : Boton Nuevo Cliente

### ISSUE THREAD

**Issue by cristianaltamirano** [111utn/app-pizzeria#25]
Tipo: Boton

**Comment by cristianaltamirano** [comment]
Cerrado por estar repetido con Issue #20

**Comment by eridal** [comment]
Buen ojo @cristianaltamirano 

Este issue deberia ser `Boton nuevo Cliente` .. corrigiendo en instantes!

**Comment by eridal** [comment]
Duplicado de #45
