### ISSUE TITLE
NuevoClienteView: Boton Cancelar

### ISSUE THREAD

**Issue by eridal** [111utn/app-pizzeria#31]

**Comment by eridal** [comment]
Agus,

Te asigno este boton en una ventana que todavia no existe.. podes crearla junto a `CajeroView`?

El nombre de la ventana es `NuevoClienteView` y Andres va a abrirla con el boton de  #45

**Comment by Agus12s** [comment]
Hola Martín. Desconozco si me perdí una clase donde hablaban de swing pero
me está resultando muy difícil entender como funciona, algún tutorial o
manual de 111mil que lo explique? Estoy armando cajero view actualmente.

**Comment by eridal** [comment]
Podes fíjarte como están hechas las otras ventanas?

Cuidado q `CajeroView` ya existe. No dupliques trabajo ;)
