### ISSUE TITLE
Crear Main

### ISSUE THREAD

**Issue by eridal** [111utn/app-pizzeria#4]
Completar la clase: https://github.com/111utn/app-pizzeria/blob/master/src/utn111/pizzeria/Pizzeria.java

**Comment by eridal** [comment]
Vamos a cambiar el nombre **dueño** por **admin**, para evitar tener conflictos con la letra `n`

**Comment by pablopetito** [comment]
Ok. Una pregunta por el trow cuando no se agregan argumentos o e null, que excepción tenia que lanza que no lo recuerdo ??

**Comment by pablopetito** [comment]
perdón throw ....

**Comment by eridal** [comment]
Podes lanzar `IllegalArgumentException` para señalizar que no recibiste el argumento correcto. No es importante el mensaje de error.

**Comment by pablopetito** [comment]
ok

**Comment by eridal** [comment]
Cerrado por #7
