### ISSUE TITLE
Cambiar setBounds por Layout Manager en CocinaView

### ISSUE THREAD

**Issue by Agus12s** [111utn/app-pizzeria#67]

**Comment by eridal** [comment]
Creaste un issue vacio? Tenias intencion de crear un PR?

**Comment by Agus12s** [comment]
Hola, Cree hace no mucho el #67 ("Cambiar setBounds por Layout Manager en
CocinaView"), pero no entiendo por que vacío. y tenia intenciones de hacer
un pr, de hecho. pushee en mi repo, pero como no esta completo como para
mergear no hice el PR. Tuve un par de problemas con el gridBagLayout.

2018-05-20 23:31 GMT-03:00 Martin <notifications@github.com>:
